name: Build Acurast Script
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./processor

jobs:
  build-script:
    name: Build and upload Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Link Utils (1/2)
        run: yarn link
        working-directory: ./shared_utils
      - name: Link Utils (2/2)
        run: yarn link "acurast-mandelbrot-utils"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run bundle
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: "./processor/dist"
